DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  building_code VARCHAR(255) NOT NULL,
  fname VARCHAR(255) NOT NULL,
  lname VARCHAR(255) NOT NULL,
  email TEXT,
  password VARCHAR(255) NOT NULL,
  phone_number VARCHAR(255) NOT NULL,
  unit_number VARCHAR(40) NOT NULL,
  is_admin BOOLEAN NOT NULL DEFAULT FALSE
);

