DROP TABLE IF EXISTS amenities CASCADE;

CREATE TABLE amenities (
  id SERIAL PRIMARY KEY NOT NULL,
  building_id VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  image TEXT,
  capacity int,
  open_time TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  close_time TIMESTAMP WITH TIME ZONE DEFAULT NOW() + time '16:00'
);

